### ISSUE TITLE
Regulation

### ISSUE THREAD

**Issue by techmaved** [2223-Project-1/OmegaPass#32]
- Imprint
- data protection
- cookie banner

**Comment by Fovty** [comment]
1/3 cookie banner implemented

**Comment by lvlcn-t** [comment]
2/3 imprint in [feat/regulation#32](https://github.com/2223-Project-1/OmegaPass/tree/feat/regulation%2332)

**Comment by lvlcn-t** [comment]
3/3 privacy policy in [feat/regulation#32](https://github.com/2223-Project-1/OmegaPass/tree/feat/regulation%2332)
