### ISSUE TITLE
Proper exception handling and catching

### ISSUE THREAD

**Issue by lvlcn-t** [2223-Project-1/OmegaPass#59]
**Is your feature request related to a problem? Please describe.**
We need proper exception handling and catching.

**Describe the solution you'd like**
After catching an exception log the exception.

**Describe alternatives you've considered**
After catching an exception output an error. (And if not too sensible output the exception)

**Additional context**
Please provide other solutions you would like to implement if you have any.

**Comment by techmaved** [comment]
@lvlcn-t you added error handling kind of in #52
